# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapp-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - webtestgp-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:SkipExtraFilesOnServer=True /p:_PackageTempDir="\webtestgp-master\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: webtestgp-master
          path: '/webtestgp-master/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webtestgp-master
          path: webtestgp-master

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webtestgp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.WEBTESTGP_MASTER }}
          package: D:\a\app-service-web-dotnet-get-started-1\app-service-web-dotnet-get-started-1\
